### ISSUE TITLE
It only downloads a 1kb mp3 file

### ISSUE THREAD

**Issue by InspiringOwl44** [realcoloride/khinseiderantiredirect#1]
I tried the script hoping to fix the redirection issue, but when it downloads the mp3 file, this is a 1kb file.

**Comment by realcoloride** [comment]
Hey there! I'll investigate on it right now and fix this bug.

**Comment by realcoloride** [comment]
Hello there, Upon testing, doing right click save as seemed to have worked correctly. Could you link to me the album or game and track you've tried to download?

**Comment by InspiringOwl44** [comment]
Sure, here it is :)
https://downloads.khinsider.com/game-soundtracks/album/starcraft-2-wings-of-liberty-gamerip
It works if you, indeed, use right-click on the save button and click on Save target as, but clicking the icon does what I said earlier.

**Comment by realcoloride** [comment]
Oh right, so the icon is not downloading or is downloading an incorrect file correct?

That could be caused by cross site content policy. I could make a patch for it that uses elevated tampermonkey requesting privileges if needed (like i do for my other scripts).

**Comment by InspiringOwl44** [comment]
Is downloading an incorrect file, that's right.
Surely is trying to download an mp3 file, but as I said, it's only 1kb.

**Comment by realcoloride** [comment]
Hey there! I am pushing a fix soon that will allow you to download by clicking directly without having to right click and save as. I will keep you updated!

**Comment by realcoloride** [comment]
https://github.com/realcoloride/khinsiderantiredirect/assets/108619637/d24b1d37-92b5-4925-b178-bd58b4a5f114

Hey there. Here is a short demo of what it looks like now. I will do some QA and bug testing and i'll publish.

**Comment by InspiringOwl44** [comment]
Excellent! Thank you very much, very glad the script is very much alive :)

**Comment by realcoloride** [comment]
No problem! It is a pleasure to make these scripts.

I have commited https://github.com/realcoloride/khinsiderantiredirect/commit/e0b599f3cb405c1335da1a797e96146c26d90702. Please download the version and test it out and let me know if it works correctly for you.

**Comment by InspiringOwl44** [comment]
Yes, now it's working properly.
Once again, thank you very much <3

**Comment by realcoloride** [comment]
No problem! Thanks for the contribution to the project. Make sure to star this repository if you like it and share it!
Feel also free to check [my other scripts here](https://greasyfork.org/users/1070263-realcoloride).

The update will be pushed and ready to use for others soon. If you have other questions or another problem to report, feel free to re-open an issue.
