### ISSUE TITLE
Doesn't work in all soundtracks

### ISSUE THREAD

**Issue by InspiringOwl44** [realcoloride/khinseiderantiredirect#2]
Hi again.

I noticed that in some soundtrack pages, the script doesn't work as intended.

For example, in the following ost: [https://downloads.khinsider.com/game-soundtracks/album/x-men-vs.-street-fighter-1996](url), I can use the script fine, but in [https://downloads.khinsider.com/game-soundtracks/album/marvel-super-heroes-vs-street-fighter-original-sound-track-arrange](url), it shows this error when trying to download a track:

![image](https://github.com/user-attachments/assets/64cf4563-0dfc-47f7-afc1-27b5fb231f27)

I can download the track the old way (clicking the track and saving the MP3 directly).

**Comment by realcoloride** [comment]
![image](https://github.com/user-attachments/assets/4860d9ba-cd50-4943-92d9-f8f1a42cdabc)
Just a domain that was not in the list. I added it and I will push an update soon.

EDIT: problem fixed. You can Update now.

**Comment by InspiringOwl44** [comment]
Working flawlessly. Thank you very much ♥
